### ISSUE TITLE
Long SMS that needs fragmentation do not go through

### ISSUE THREAD

**Issue by phsultan** [voxbone/voxsms-npm#2]
Hi,

Long messages do not reach the destination, although they are accepted by Voxbone.

We're testing to destination (french) numbers here, one of them is receiving the fragmented messages but the other one is not.

When we send shorter enough SMS, it reaches any destination (log taken from package):

```
Encoding: gsma Frag Length: 160 msg length: 18 Frag Ref: 284766
...
[DEBUG] POST https://81.201.82.10:4443/sms/v1/33XXXXXXXXX succeeded with HTTP status 202
{ transaction_id: '75d0467e39ab476e8a1669fd2020d740' }
```

Now, sending a long message that needs to be fragmented results in sending two requests (with two separate transaction IDs), but never makes it to the number 33XXXXXXXXX:

```
Encoding: gsma Frag Length: 152 msg length: 161 Frag Ref: 213173
...
[DEBUG] POST https://81.201.82.10:4443/sms/v1/33XXXXXXXXX succeeded with HTTP status 202
{ transaction_id: '16fdbdd776cd406c9ce2937f4bfacd44' }
[DEBUG] POST https://81.201.82.10:4443/sms/v1/33XXXXXXXXX succeeded with HTTP status 202
{ transaction_id: '57b994dff5aa44c2981c457cb447cc6d' }
```

Also, in our Voxbone console, all the (fragmented) SMS are properly logged with a `Success`status just as if they had been successfully sent and received.

Is there any way to get an information back from Voxbone for us to know if the message was not delivered ?

Looking forward to meet @sachanacar and/or @vmorsiani this weekend in Paris for the TADHack :)

Thanks for your help !

**Comment by vmorsiani** [comment]
Hello,

2 things could potentially go wrong here:
1) either fragmentation information is wrongly set by the library. So the carrier expect another fragment before actually delivering the message
2) the lib is fine but there's an issue with our interconnection

I'll perform a few tests to validate the way we do fragmentation with the node library and if it appears to be fine, I'll ask you to open a ticket with Voxbone.

> Is there any way to get an information back from Voxbone for us to know if the message was not delivered ?

The way to achieve the above would be to request a delivery report

I'll get back to you as soon as I'm done validating the way we do fragmentation within the library.

**Comment by vmorsiani** [comment]
OK, I tested the library and it succeeded for me. 
The sms got properly delivered to my phone.

```
Encoding: gsma Frag Length: 152 msg length: 924 Frag Ref: 213173
[ 'this should be a very long message which gets fragmented. this should be a very long message which gets fragmented. this should be a very long message w',
  'hich gets fragmented. this should be a very long message which gets fragmented.this should be a very long message which gets fragmented. this should be ',
  'a very long message which gets fragmented. this should be a very long message which gets fragmented. this should be a very long message which gets fragm',
  'ented.this should be a very long message which gets fragmented. this should be a very long message which gets fragmented. this should be a very long mes',
  'sage which gets fragmented. this should be a very long message which gets fragmented.this should be a very long message which gets fragmented. this shou',
  'ld be a very long message which gets fragmented. this should be a very long message which gets fragmented. this should be a very long message which gets',
  ' fragmented.' ]
User Agent: VoxSMS - NPM 1.0.9
User Agent: VoxSMS - NPM 1.0.9
User Agent: VoxSMS - NPM 1.0.9
User Agent: VoxSMS - NPM 1.0.9
User Agent: VoxSMS - NPM 1.0.9
User Agent: VoxSMS - NPM 1.0.9
User Agent: VoxSMS - NPM 1.0.9
[DEBUG] POST https://81.201.82.10:4443/sms/v1/32XXXXXXXXX succeeded with HTTP status 202
{ transaction_id: 'b52794eb721e49d3aea5f3155ffd02da' }
[DEBUG] POST https://81.201.82.10:4443/sms/v1/32XXXXXXXXX succeeded with HTTP status 202
{ transaction_id: '67875abde1f440a9a941275c6788df86' }
[DEBUG] POST https://81.201.82.10:4443/sms/v1/32XXXXXXXXX succeeded with HTTP status 202
{ transaction_id: '0df373176bb3483898a01f8f315691d7' }
[DEBUG] POST https://81.201.82.10:4443/sms/v1/32XXXXXXXXX succeeded with HTTP status 202
{ transaction_id: '29ae7f50122341a08fb0368cf4347639' }
[DEBUG] POST https://81.201.82.10:4443/sms/v1/32XXXXXXXXX succeeded with HTTP status 202
{ transaction_id: '1df92294da344f0e985a85e0e1ed0a77' }
[DEBUG] POST https://81.201.82.10:4443/sms/v1/32XXXXXXXXX succeeded with HTTP status 202
{ transaction_id: '35f7c08d67d44ed7b56c67e04c232ebd' }
[DEBUG] POST https://81.201.82.10:4443/sms/v1/32XXXXXXXXX succeeded with HTTP status 202
{ transaction_id: 'f04600920667409caf0a0f2110d3365e' }
```

I noticed a bug with the library tho, the generated frag ref = 213173
Normally frag ref should be a value between 0 and 65535.

The VoxSMS platform do compensate for that (validated by reusing the same frag reference as you used). So if the value is out of range, it accommodates with it
I'll patch the lib to ensure generated frag refence are within bounds.

May I suggest you open a ticket toward Voxbone support and report your issue as it seems the issue is on the interconnection side

**Comment by phsultan** [comment]
Indeed, I will open a ticket at Voxbone. Thanks a lot @vmorsiani

**Comment by vmorsiani** [comment]
Thanks!

I  pushed the fix for the wrongly generated frag ref.
As this issue is not a "blocker" I'll wait a bit more before asking @sachanacar to push a new version to npmjs
